import "./globals.css";
import { Inter } from "next/font/google";
import GlobalRecoilRoot from "./recoilRoot/GlobalRecoilRoot";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Animesh's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-bgCol">
        <GlobalRecoilRoot>{children}</GlobalRecoilRoot>
      </body>
    </html>
  );
}
